### ISSUE TITLE
Ordering Service Error Code: 20

### ISSUE THREAD

**Issue by sdejea6** [ibm-workshop/bda#1]
<img width="1280" alt="Screen Shot 2021-07-12 at 9 49 42 PM" src="https://user-images.githubusercontent.com/86389806/125510825-8fc10a3b-1be0-441a-90e3-5ecd0849b5e1.png">

When creating an ordering service, I am met with the following error:

REQUEST_ERROR_IN_RESPONSE: POST /api/saas/v3/components failed with 500: Internal Server Error
failed to reconcile node: Code: 21 - failed to initialize orderer node: failed to enroll with CA: Response from server: Error Code: 20 - Authentication failure

**Comment by marek5050** [comment]
@sdejea6  interesting it says it's an authentication issue, that's probably some password or you are using the wrong user to create the service.... you might need to recreate the CA and Orderer.. Please make sure you follow the instructions exactly... it's a bit difficult to troubleshoot these problems and the main solution is to rebuild

**Comment by marek5050** [comment]
@sdejea6 why is your enroll id `ordered`? 
![image](https://user-images.githubusercontent.com/6081895/125511948-6ad57031-f480-4c63-b168-d5c0427137bb.png)

**Comment by marek5050** [comment]
Closing issue. Everything was okay after rebuilding network.
